version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"  # 修改為使用 Render 提供的 PORT 變數，默認為 8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JACKSON_TIME_ZONE: GMT+8
      SPRING_JACKSON_DATE_FORMAT: yyyy-MM-dd HH:mm:ss
      SERVER_ADDRESS: 0.0.0.0   # 確保服務綁定到所有網絡接口
      SERVER_PORT: ${PORT:-8080}  # 使用 Render 提供的 PORT 變數

  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: mall
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: